name: Build Docker Image
on:
  push:
    paths:
      - 'Dockerfile'      
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      permissions:
        packages: write
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t ${{ github.repository }}
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{ github.repository }}
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build & Publish Docker Image
          uses: docker/build-push-action@v6
          with:
              push: true
              platforms: linux/amd64
              tags: ghcr.io/${{ github.repository }}    
